### PR TITLE
Remove signatures from README

### PR DESCRIPTION
**Pull request by kittens**
The current signature list in the README is frozen in preference of the Google form. The existing list now comes across as elitist and alienates people who have signed the form as they "aren't good enough" to be on the main list.

The Google spreadsheet now has 500+ signatures and GitHub has responded so I don't think the inclusion of a limited list is required for any influence.

### CODE REVIEW

**Comment by joshmanders** [comment]
Highly agree with this.

**Comment by samccone** [comment]
yap

**Comment by jamonholmgren** [comment]
The "me too" comments above are ironic. ;)

**Comment by joshmanders** [comment]
@jamonholmgren Calm down, Alanis Morissette. 🎯

**Comment by una** [comment]
:+1: The ability to join the list should come before a list of signatures. Also the separation of "primary" signatures and "the rest" isn't necessary. A developer doesn't realize they can even join in to sign until they click into the doc link anyway, so all for this PR :clap:

**Comment by joshmanders** [comment]
That `README.md` looks absolutely beautiful now.

**Comment by samccone** [comment]
+1

**Comment by joshmanders** [comment]
@samccone to drive it home!

**Comment by jamonholmgren** [comment]
It's like raiiinnnnn

**Comment by ghpabs** [comment]
> ... and GitHub has responded

Is there a link to GitHub's response?

**Comment by joshmanders** [comment]
https://news.ycombinator.com/item?id=10905338

**Comment by joshmanders** [comment]
@jonobacon responded on the Hacker News thread: https://news.ycombinator.com/item?id=10905338

**Pull request merged**
