### PR TITLE
Sign, on behalf of TShock & Nyx Studios

### PR DESCRIPTION
**Pull request by nicatronTg**
Hi, I'd like to sign on behalf of NyxStudios/TShock (550 stars, 3.3k commits).

### CODE REVIEW

**Comment by nicatronTg** [comment]
Asdf, now there's a google forms link

**Comment by nicatronTg** [comment]
Reopening because the google forms link is "not accepting new responses."

**Comment by joshmanders** [comment]
Works now, try again.

**Comment by nicatronTg** [comment]
Done :)

**Pull request closed without merging**
