### PR TITLE
OK, TODO list?

### PR DESCRIPTION
**Pull request by LeoColomb**
Flirting with the arrogance. 

https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by joshmanders** [comment]
Not sure what you mean by "Flirting with the arrogance"

**Comment by aensley** [comment]
Meaning, they addressed 1 and 3. Now just waiting for 2.

**Comment by rom1504** [comment]
And 2 is now done!

**Comment by ZakariaRidouh** [comment]
@LeoColomb #2 is done now! Please update this PR :smile:

**Pull request closed without merging**
