### PR TITLE
Are you there? Update

### PR DESCRIPTION
**Pull request by nzakas**
I made an attempt at an update. Feedback welcome.

@thejameskyle @kangax @dmethvin (those are the only ones I can remember off the top of my head, sorry!)

### CODE REVIEW

**Comment by thejameskyle** [comment]
We should discuss this separately and I don't think its appropriate to add people to signatures when they haven't even read it. Create a google doc and invite people to discuss

**Comment by nzakas** [comment]
I was just trying to get the ball rolling by using the original template. The point of sharing it was to give it some visibility so we could discuss. If you want to do it another way, go for it.

**Comment by thejameskyle** [comment]
I started a google doc and invited all the original authors.

**Comment by nzakas** [comment]
Thanks!

**Pull request closed without merging**
