### PR TITLE
Add myself as a signatory

### PR DESCRIPTION
**Pull request by cvrebert**
(In a personal capacity. I don't speak for the Bootstrap Core Team as a whole.)

### CODE REVIEW

**Comment by thejameskyle** [comment]
Can you rebase, you removed another signature

**Comment by cvrebert** [comment]
(Diff has deletion since I'm on mobile and this file is getting frequently updated.)

**Comment by thejameskyle** [comment]
I'll fix it up locally then

**Comment by thejameskyle** [comment]
Done

**Comment by cvrebert** [comment]
Thank you much!

**Pull request closed without merging**
