### PR TITLE
Add Nikolai Vazquez (nvzqz)

### PR DESCRIPTION
**Pull request by nvzqz**

### CODE REVIEW

**Comment by joshmanders** [comment]
Use this form instead of PR. http://goo.gl/forms/DtmQnUXNSE

**Comment by nvzqz** [comment]
Done, thanks

**Comment by tekknolagi** [comment]
@joshmanders how does this form verify the user actually wants to sign?

**Comment by joshmanders** [comment]
@tekknolagi Honestly you don't know. I guess it's in good faith that nobody's maliciously putting others names on it? Maybe @thejameskyle can weigh in better.

**Comment by thejameskyle** [comment]
idk how to validate that

**Comment by jtmarmon** [comment]
put a file on the form and make them digitally sign it with their public gh ssh key? probably more work than merging PRs but at least you could automate it

**Pull request closed without merging**
